CineMatch: CineMatch.views Namespace Reference
CineMatch.views Namespace Reference
Functions
home (request)
Maps index html to home url.
signin (request)
sign in information requested, maps sign in html to sign in url
signup (request)
sign up information requested, maps sign up html to sign up url
signout (request)
sign out requested, maps sign out html to home
activate (request, uidb64, token)
profile (request)
search (request)
Questionnaire query initialized, maps search html to search url.
continue_to_search (request)
get_movie_recommendations (request, actor, director, genre)
function to query database for filters.
add_to_favorite (request, movie_id, movie_title)
fetch_movie_data (genre_id, actor_id=None, director_id=None)
function to query database for movie data ids
fetch_genre_id (genre_name)
function to query database for genre id.
fetch_actor_id (actor_name)
function to query database for actor id searched.
fetch_director_id (director_name)
function to query database for directors id searched.
fetch_actor_movies (actor_name)
function to query database for actors searched.
fetch_actor_genre_movies (actor_name, genre_name)
function to query database for actors and genres commonalities.
fetch_director_movies (director_name)
function to query database for directors searched.
fetch_movies_for_actor_in_director (actor_name, director_name)
function to query database for actors and directors commonalities.
Variables
str TMDB_BASE_URL = 'https://api.themoviedb.org/3/'
initialize url for movie database
int movie_num = 100
Function Documentation
activate()
CineMatch.views.activate (request, uidb64, token)
add_to_favorite()
CineMatch.views.add_to_favorite (request, movie_id, movie_title)
continue_to_search()
CineMatch.views.continue_to_search (request)
fetch_actor_genre_movies()
CineMatch.views.fetch_actor_genre_movies (actor_name, genre_name)
function to query database for actors and genres commonalities.
Parameters
request send information to server.
Returns
movie data fetched.
Referenced by CineMatch.views.get_movie_recommendations().
fetch_actor_id()
CineMatch.views.fetch_actor_id (actor_name)
function to query database for actor id searched.
Parameters
request send information to server.
Returns
movie data fetched.
fetch_actor_movies()
CineMatch.views.fetch_actor_movies (actor_name)
function to query database for actors searched.
Parameters
request send information to server.
Returns
movie data fetched.
fetch_director_id()
CineMatch.views.fetch_director_id (director_name)
function to query database for directors id searched.
Parameters
request send information to server.
Returns
movie data fetched.
Referenced by CineMatch.views.fetch_movies_for_actor_in_director().
fetch_director_movies()
CineMatch.views.fetch_director_movies (director_name)
function to query database for directors searched.
Parameters
request send information to server.
Returns
movie data fetched.
fetch_genre_id()
CineMatch.views.fetch_genre_id (genre_name)
function to query database for genre id.
Parameters
request send information to server.
Returns
movie data fetched.
Referenced by CineMatch.views.search().
fetch_movie_data()
CineMatch.views.fetch_movie_data (genre_id, actor_id = None, director_id = None)
function to query database for movie data ids
Parameters
request send information to server.
Returns
movie data fetched.
fetch_movies_for_actor_in_director()
CineMatch.views.fetch_movies_for_actor_in_director (actor_name, director_name)
function to query database for actors and directors commonalities.
Parameters
request send information to server.
Returns
movie data fetched.
References CineMatch.views.fetch_director_id().
Referenced by CineMatch.views.get_movie_recommendations().
get_movie_recommendations()
CineMatch.views.get_movie_recommendations (request, actor, director, genre)
function to query database for filters.
Parameters
request send information to server.
Returns
movie data fetched.
References CineMatch.views.fetch_actor_genre_movies(), and CineMatch.views.fetch_movies_for_actor_in_director().
home()
CineMatch.views.home (request)
Maps index html to home url.
Parameters
request send information to server.
Returns
render HttpResponse object.
profile()
CineMatch.views.profile (request)
search()
CineMatch.views.search (request)
Questionnaire query initialized, maps search html to search url.
Parameters
request send information to server.
Returns
render HttpResponse object.
References CineMatch.views.fetch_genre_id().
signin()
CineMatch.views.signin (request)
sign in information requested, maps sign in html to sign in url
Parameters
request send information to server.
Returns
render HttpResponse object.
signout()
CineMatch.views.signout (request)
sign out requested, maps sign out html to home
Parameters
request send information to server.
Returns
redirect to home.
render HttpResponse object.
signup()
CineMatch.views.signup (request)
sign up information requested, maps sign up html to sign up url
Parameters
request send information to server.
Returns
render HttpResponse object.
Variable Documentation
movie_num
int CineMatch.views.movie_num = 100
TMDB_BASE_URL
str CineMatch.views.TMDB_BASE_URL = 'https://api.themoviedb.org/3/'
initialize url for movie database